name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository'
        required: true
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
        repository: ${{ inputs.repo }}
    - run: ls
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
